"""Bundle the app into one file: `streamlit_app.py`.

    python3 build_single_file.py

Deploying three .py files that must match is easy to get wrong — copy one and
forget another and the app dies with an AttributeError. This packs race_core.py
and game_html.py into the app file itself, so there is exactly one file to
upload and nothing that can fall out of step.

The two modules are embedded as base64 (safe for any quoting inside them) and
registered in sys.modules before the app code runs, so `import race_core` and
`from game_html import build_game_html` keep working unchanged.
"""

import base64
import os

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "streamlit_app.py")

HEADER = '''"""
Turbo Racing League — single-file Streamlit app.

    pip install streamlit pandas "qrcode[pil]"
    streamlit run streamlit_app.py

Generated by build_single_file.py — it bundles race_core.py and game_html.py
into this file so there is only ever one file to deploy. Edit the source files
and re-run the builder rather than editing this one.
"""

from __future__ import annotations       # must sit right after the docstring

import base64 as _b64
import sys as _sys
import types as _types

_BUNDLED = {
%s}


def _install_bundled():
    """Register the embedded modules so normal imports find them."""
    for _name in ("game_html", "race_core"):
        if _name in _sys.modules:
            continue
        _mod = _types.ModuleType(_name)
        _mod.__file__ = __file__
        _src = _b64.b64decode(_BUNDLED[_name]).decode("utf-8")
        exec(compile(_src, _name + ".py (bundled)", "exec"), _mod.__dict__)
        _sys.modules[_name] = _mod


_install_bundled()

# --------------------------------------------------------------------------
# app.py
# --------------------------------------------------------------------------
'''


def main():
    parts = []
    for name in ("game_html", "race_core"):
        src = open(os.path.join(HERE, name + ".py"), encoding="utf-8").read()
        blob = base64.b64encode(src.encode("utf-8")).decode("ascii")
        chunks = [blob[i:i + 76] for i in range(0, len(blob), 76)]
        joined = "\n        ".join('"%s"' % c for c in chunks)
        parts.append('    "%s":\n        %s,\n' % (name, joined))

    app_src = open(os.path.join(HERE, "app.py"), encoding="utf-8").read()
    # Its docstring is replaced by the bundle header, and the __future__ import
    # has to move to the top of the generated file (it is already there).
    if app_src.startswith('"""'):
        app_src = app_src[app_src.index('"""', 3) + 3:].lstrip("\n")
    app_src = app_src.replace("from __future__ import annotations\n", "", 1).lstrip("\n")

    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write(HEADER % "".join(parts))
        fh.write(app_src)

    size = os.path.getsize(OUT)
    print(f"wrote {OUT} ({size:,} bytes)")


if __name__ == "__main__":
    main()
